import { createFileRoute } from "@tanstack/react-router";
import { AppHeader } from "@/components/AppHeader";
import { CommunityGallery } from "@/components/CommunityGallery";

export const Route = createFileRoute("/gallery")({
  component: GalleryRoute,
  head: () => ({
    meta: [
      { title: "Gallery — Polyfy" },
      { name: "description", content: "Explore stunning 3D models generated by the Polyfy community." },
    ],
  }),
});

function GalleryRoute() {
  return (
    <div className="min-h-screen">
      <AppHeader
        showReset={false}
        onReset={() => {}}
      />
      <main className="pt-12">
        <CommunityGallery />
      </main>
    </div>
  );
}
