import { useState, useEffect, useCallback } from "react";
import { Loader2, Star, X, Box, User, Calendar, Plus } from "lucide-react";
import { supabase } from "@/lib/supabase";
import type { Creation, Review } from "@/lib/supabase";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

interface CreationWithReviews extends Creation {
  reviews?: Review[];
}

const ITEMS_PER_PAGE = 12;

export function CommunityGallery() {
  const [creations, setCreations] = useState<CreationWithReviews[]>([]);
  const [loading, setLoading] = useState(true);
  const [loadingMore, setLoadingMore] = useState(false);
  const [hasMore, setHasMore] = useState(true);
  const [page, setPage] = useState(0);
  const [sortBy, setSortBy] = useState<string>("featured");
  const [useFallbackTable, setUseFallbackTable] = useState(false);
  
  const [selectedCreation, setSelectedCreation] = useState<CreationWithReviews | null>(null);

  const fetchCreations = useCallback(async (pageIndex: number, isInitial = false) => {
    if (isInitial) setLoading(true);
    else setLoadingMore(true);

    const from = pageIndex * ITEMS_PER_PAGE;
    const to = from + ITEMS_PER_PAGE - 1;

    try {
      const tableToQuery = useFallbackTable ? "creations" : "creations_with_stats";
      let query = supabase
        .from(tableToQuery)
        .select("*, reviews(*)", { count: "exact" })
        .eq("is_approved", true)
        .eq("status", "complete");

      // Apply ordering
      if (sortBy === "featured") {
        query = query
          .order("display_order", { ascending: true })
          .order("created_at", { ascending: false });
      } else if (sortBy === "newest") {
        query = query.order("created_at", { ascending: false });
      } else if (sortBy === "oldest") {
        query = query.order("created_at", { ascending: true });
      } else if (sortBy === "alpha_asc") {
        query = query
          .order("object_label", { ascending: true })
          .order("created_at", { ascending: false });
      } else if (sortBy === "alpha_desc") {
        query = query
          .order("object_label", { ascending: false })
          .order("created_at", { ascending: false });
      } else if (sortBy === "rating_desc") {
        if (!useFallbackTable) {
          query = query
            .order("avg_rating", { ascending: false })
            .order("created_at", { ascending: false });
        } else {
          query = query.order("created_at", { ascending: false });
        }
      } else if (sortBy === "rating_asc") {
        if (!useFallbackTable) {
          query = query
            .order("avg_rating", { ascending: true })
            .order("created_at", { ascending: false });
        } else {
          query = query.order("created_at", { ascending: false });
        }
      }

      const { data, error } = await query.range(from, to);

      if (error) {
        // Fallback if view doesn't exist yet
        if (!useFallbackTable && (error.code === "P0001" || (error.message?.includes("relation") && error.message?.includes("does not exist")))) {
          console.warn("View 'creations_with_stats' not found, falling back to 'creations' table.");
          setUseFallbackTable(true);
          return;
        }
        throw error;
      }

      const newItems = (data as CreationWithReviews[]) ?? [];
      
      if (isInitial) {
        setCreations(newItems);
      } else {
        setCreations((prev) => [...prev, ...newItems]);
      }

      if (newItems.length < ITEMS_PER_PAGE) {
        setHasMore(false);
      } else {
        setHasMore(true);
      }
    } catch (err) {
      console.error("Error fetching gallery:", err);
    } finally {
      if (isInitial) setLoading(false);
      else setLoadingMore(false);
    }
  }, [sortBy, useFallbackTable]);

  useEffect(() => {
    fetchCreations(0, true);
    setPage(0);
  }, [fetchCreations]);

  const handleLoadMore = () => {
    const nextPage = page + 1;
    setPage(nextPage);
    fetchCreations(nextPage, false);
  };

  const getAverageRating = (reviews?: Review[]) => {
    if (!reviews || reviews.length === 0) return 0;
    const sum = reviews.reduce((acc, r) => acc + (r.rating || 0), 0);
    return sum / reviews.length;
  };

  return (
    <div className="w-full max-w-7xl mx-auto px-4 py-8">
      <div className="mb-8 flex flex-col md:flex-row md:items-end justify-between gap-4 border-b border-white/8 pb-6">
        <div className="text-center md:text-left">
          <h1 className="text-3xl md:text-4xl font-bold tracking-tight text-foreground font-mono bg-gradient-to-r from-white to-white/70 bg-clip-text text-transparent">
            Community Gallery
          </h1>
          <p className="mt-2 text-tech-muted text-sm font-mono">
            Explore stunning 3D models generated by the Polyfy community.
          </p>
        </div>

        {/* Sort Filter Dropdown */}
        <div className="flex items-center justify-center md:justify-end gap-2.5 font-mono text-xs">
          <span className="text-white/40 uppercase tracking-wider font-bold text-[10px]">Sort By:</span>
          <select
            value={sortBy}
            onChange={(e) => setSortBy(e.target.value)}
            className="bg-black/60 border border-white/10 hover:border-primary/40 text-tech-fg rounded-xl px-3 py-2 text-xs font-semibold focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary/20 cursor-pointer transition-all duration-300 shadow-lg"
          >
            <option value="featured" className="bg-[#0c0c0c] text-white">Featured (Admin Pick)</option>
            <option value="newest" className="bg-[#0c0c0c] text-white">Newest First</option>
            <option value="oldest" className="bg-[#0c0c0c] text-white">Oldest First</option>
            {!useFallbackTable && (
              <>
                <option value="rating_desc" className="bg-[#0c0c0c] text-white">Highest Rating</option>
                <option value="rating_asc" className="bg-[#0c0c0c] text-white">Lowest Rating</option>
              </>
            )}
            <option value="alpha_asc" className="bg-[#0c0c0c] text-white">Alphabetical (A - Z)</option>
            <option value="alpha_desc" className="bg-[#0c0c0c] text-white">Alphabetical (Z - A)</option>
          </select>
        </div>
      </div>

      {loading ? (
        <div className="flex items-center justify-center py-20">
          <Loader2 className="w-8 h-8 animate-spin text-primary/50" />
        </div>
      ) : creations.length === 0 ? (
        <div className="text-center py-20 border border-white/10 rounded-2xl bg-white/5 backdrop-blur-sm">
          <Box className="w-12 h-12 text-tech-muted/50 mx-auto mb-4" />
          <p className="text-tech-muted font-mono">No community creations available yet.</p>
        </div>
      ) : (
        <>
          <div className="flex flex-col gap-4">
            {creations.map((c) => {
              const avgRating = getAverageRating(c.reviews);
              return (
                <div
                  key={c.id}
                  onClick={() => setSelectedCreation(c)}
                  className="flex flex-col md:flex-row bg-white/3 border border-white/8 rounded-2xl overflow-hidden hover:border-primary/40 hover:shadow-[0_0_20px_rgba(var(--primary-rgb),0.15)] transition-all duration-300 cursor-pointer group relative"
                >
                  {/* 1. Input image (Left) */}
                  {c.original_image_url && (
                    <div className="w-full md:w-48 shrink-0 bg-black/30 flex items-center justify-center border-b md:border-b-0 md:border-r border-white/8">
                      <img
                        src={c.original_image_url}
                        alt="Input"
                        className="w-full h-48 md:h-full object-cover md:max-h-full group-hover:scale-105 transition-transform duration-700 ease-out"
                      />
                    </div>
                  )}

                  {/* 2. 3D model viewer (Middle) */}
                  <div className="w-full h-64 md:flex-1 md:h-auto md:min-h-[220px] bg-black/10 relative">
                    {c.raw_glb_url || c.glb_model_url ? (
                      <model-viewer
                        src={c.raw_glb_url ?? c.glb_model_url}
                        auto-rotate="true"
                        camera-controls="true"
                        loading="lazy"
                        style={{ width: "100%", height: "100%", background: "transparent" }}
                      />
                    ) : (
                      <div className="w-full h-full flex items-center justify-center text-xs text-tech-muted/50 font-mono">
                        Model not available
                      </div>
                    )}

                    {/* Label & Date overlay */}
                    <div className="absolute bottom-2 left-2 bg-black/60 backdrop-blur-sm px-3 py-1.5 rounded-lg flex flex-col gap-0.5">
                      <span className="text-sm font-bold font-mono text-white">{c.object_label || "Untitled Model"}</span>
                      <span className="text-[10px] font-mono text-tech-muted">{new Date(c.created_at || "").toLocaleDateString()}</span>
                    </div>
                    
                    {/* Hover indicator overlay */}
                    <div className="absolute inset-0 pointer-events-none bg-black/0 group-hover:bg-black/10 transition-colors duration-300 flex items-center justify-center opacity-0 group-hover:opacity-100">
                       <div className="bg-primary/90 text-primary-foreground px-4 py-2 rounded-full font-mono text-sm font-semibold flex items-center gap-2 transform translate-y-4 group-hover:translate-y-0 transition-transform duration-300 shadow-xl">
                          <Box className="w-4 h-4" /> View Full Details
                       </div>
                    </div>
                  </div>

                  {/* 3. Review / Feedback Panel (Right) */}
                  <div className="w-full md:w-72 shrink-0 p-5 border-t md:border-t-0 md:border-l border-white/8 bg-black/20 flex flex-col gap-3 font-mono">
                    <span className="text-[10px] text-white/40 uppercase tracking-widest font-bold block">Creator Review</span>
                    {c.reviews && c.reviews.length > 0 ? (
                      <div className="flex flex-col gap-2 min-w-0">
                        <div className="flex items-center justify-between gap-2">
                          <span className="text-white text-sm font-semibold truncate">
                            {c.reviews[0].reviewer_name || "Anonymous"}
                          </span>
                          <div className="flex items-center gap-0.5 shrink-0 text-yellow-400">
                            {Array.from({ length: 5 }).map((_, i) => (
                              <Star
                                key={i}
                                className={`w-3.5 h-3.5 ${
                                  i < (c.reviews?.[0]?.rating ?? 0)
                                    ? "fill-current"
                                    : "text-white/10"
                                }`}
                              />
                            ))}
                          </div>
                        </div>
                        {c.reviews[0].comment ? (
                          <p className="text-white/70 italic text-xs leading-relaxed break-words line-clamp-6">
                            "{c.reviews[0].comment}"
                          </p>
                        ) : (
                          <p className="text-white/30 italic text-[11px]">Rated without comment</p>
                        )}
                      </div>
                    ) : (
                      <span className="text-tech-muted italic text-xs mt-1">No feedback left yet.</span>
                    )}
                  </div>
                </div>
              );
            })}
          </div>

          {hasMore && (
            <div className="mt-12 flex justify-center">
              <Button 
                variant="outline" 
                onClick={handleLoadMore} 
                disabled={loadingMore}
                className="font-mono bg-white/5 border-white/10 hover:bg-white/10 w-full max-w-xs"
              >
                {loadingMore ? (
                  <><Loader2 className="w-4 h-4 mr-2 animate-spin" /> Loading...</>
                ) : (
                  <><Plus className="w-4 h-4 mr-2" /> Load More</>
                )}
              </Button>
            </div>
          )}
        </>
      )}

      {/* Detail Modal */}
      {selectedCreation && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-black/80 backdrop-blur-md animate-in fade-in duration-200">
          <div 
            className="absolute inset-0" 
            onClick={() => setSelectedCreation(null)} 
          />
          <div className="relative w-full max-w-5xl max-h-full bg-tech-bg border border-white/10 rounded-2xl shadow-2xl flex flex-col md:flex-row overflow-hidden animate-in zoom-in-95 duration-300">
            
            {/* Close button */}
            <button 
              onClick={() => setSelectedCreation(null)}
              className="absolute top-4 right-4 z-10 w-8 h-8 flex items-center justify-center rounded-full bg-black/50 text-white hover:bg-white/20 backdrop-blur-sm transition-colors"
            >
              <X className="w-4 h-4" />
            </button>

            {/* 3D Viewer Area */}
            <div className="w-full md:w-2/3 h-[40vh] md:h-[80vh] bg-black/30 relative border-b md:border-b-0 md:border-r border-white/10">
               <model-viewer
                  src={selectedCreation.raw_glb_url ?? selectedCreation.glb_model_url}
                  auto-rotate="true"
                  camera-controls="true"
                  loading="eager"
                  style={{ width: "100%", height: "100%", background: "transparent" }}
                />
            </div>

            {/* Details & Reviews Area */}
            <div className="w-full md:w-1/3 h-[50vh] md:h-[80vh] flex flex-col bg-tech-bg overflow-y-auto">
              <div className="p-6 border-b border-white/10">
                <h2 className="text-xl font-bold text-tech-fg font-mono mb-2">
                  {selectedCreation.object_label || "Untitled Model"}
                </h2>
                <div className="flex flex-col gap-2 text-xs text-tech-muted font-mono">
                  <div className="flex items-center gap-2">
                    <Calendar className="w-4 h-4 opacity-50" />
                    <span>Created on {new Date(selectedCreation.created_at || "").toLocaleDateString()}</span>
                  </div>
                  {(selectedCreation.refined_vertices || selectedCreation.raw_vertices) && (
                    <div className="flex items-center gap-2 mt-1">
                      <Box className="w-4 h-4 opacity-50" />
                      <span>{selectedCreation.refined_vertices || selectedCreation.raw_vertices} Vertices</span>
                    </div>
                  )}
                </div>
              </div>

              <div className="p-6 flex-1">
                <h3 className="text-sm font-semibold text-white/80 font-mono tracking-wider uppercase mb-4">
                  Community Feedback
                </h3>
                
                {selectedCreation.reviews && selectedCreation.reviews.length > 0 ? (
                  <div className="flex flex-col gap-4">
                    {selectedCreation.reviews.map((review) => (
                      <div key={review.id} className="bg-white/5 p-4 rounded-xl border border-white/5">
                        <div className="flex items-center justify-between mb-2">
                          <div className="flex items-center gap-2 text-xs font-semibold text-tech-fg">
                            <User className="w-3.5 h-3.5 opacity-50" />
                            {review.reviewer_name || "Anonymous"}
                          </div>
                          <div className="flex items-center gap-0.5 text-yellow-400">
                            {Array.from({ length: 5 }).map((_, i) => (
                              <Star
                                key={i}
                                className={`w-3 h-3 ${
                                  i < (review.rating ?? 0) ? "fill-current" : "text-white/10"
                                }`}
                              />
                            ))}
                          </div>
                        </div>
                        {review.comment && (
                          <p className="text-xs text-tech-muted leading-relaxed mt-2 italic">
                            "{review.comment}"
                          </p>
                        )}
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className="text-center py-10 opacity-50">
                    <Star className="w-8 h-8 mx-auto mb-2 opacity-20" />
                    <p className="text-xs font-mono">No reviews yet.</p>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
