import { useState, useEffect, useCallback } from "react";
import { Loader2, Star, X, Box, User, Calendar, Plus } from "lucide-react";
import { supabase } from "@/lib/supabase";
import type { Creation, Review } from "@/lib/supabase";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

interface CreationWithReviews extends Creation {
  reviews?: Review[];
}

const ITEMS_PER_PAGE = 12;

export function CommunityGallery() {
  const [creations, setCreations] = useState<CreationWithReviews[]>([]);
  const [loading, setLoading] = useState(true);
  const [loadingMore, setLoadingMore] = useState(false);
  const [hasMore, setHasMore] = useState(true);
  const [page, setPage] = useState(0);
  
  const [selectedCreation, setSelectedCreation] = useState<CreationWithReviews | null>(null);

  const fetchCreations = useCallback(async (pageIndex: number, isInitial = false) => {
    if (isInitial) setLoading(true);
    else setLoadingMore(true);

    const from = pageIndex * ITEMS_PER_PAGE;
    const to = from + ITEMS_PER_PAGE - 1;

    try {
      const { data, error, count } = await supabase
        .from("creations")
        .select("*, reviews(*)", { count: "exact" })
        .eq("is_approved", true)
        .eq("status", "complete")
        .order("created_at", { ascending: false })
        .range(from, to);

      if (error) throw error;

      const newItems = (data as CreationWithReviews[]) ?? [];
      
      if (isInitial) {
        setCreations(newItems);
      } else {
        setCreations((prev) => [...prev, ...newItems]);
      }

      if (count !== null && creations.length + newItems.length >= count) {
        setHasMore(false);
      } else if (newItems.length < ITEMS_PER_PAGE) {
        setHasMore(false);
      } else {
        setHasMore(true);
      }
    } catch (err) {
      console.error("Error fetching gallery:", err);
    } finally {
      if (isInitial) setLoading(false);
      else setLoadingMore(false);
    }
  }, [creations.length]);

  useEffect(() => {
    fetchCreations(0, true);
  }, [fetchCreations]);

  const handleLoadMore = () => {
    const nextPage = page + 1;
    setPage(nextPage);
    fetchCreations(nextPage, false);
  };

  const getAverageRating = (reviews?: Review[]) => {
    if (!reviews || reviews.length === 0) return 0;
    const sum = reviews.reduce((acc, r) => acc + (r.rating || 0), 0);
    return sum / reviews.length;
  };

  return (
    <div className="w-full max-w-7xl mx-auto px-4 py-8">
      <div className="mb-8 text-center md:text-left">
        <h1 className="text-3xl md:text-4xl font-bold tracking-tight text-foreground font-mono">
          Community Gallery
        </h1>
        <p className="mt-2 text-muted-foreground text-sm font-mono">
          Explore stunning 3D models generated by the Polyfy community.
        </p>
      </div>

      {loading ? (
        <div className="flex items-center justify-center py-20">
          <Loader2 className="w-8 h-8 animate-spin text-primary/50" />
        </div>
      ) : creations.length === 0 ? (
        <div className="text-center py-20 border border-white/10 rounded-2xl bg-white/5 backdrop-blur-sm">
          <Box className="w-12 h-12 text-tech-muted/50 mx-auto mb-4" />
          <p className="text-tech-muted font-mono">No community creations available yet.</p>
        </div>
      ) : (
        <>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
            {creations.map((c) => {
              const avgRating = getAverageRating(c.reviews);
              return (
                <Card 
                  key={c.id} 
                  className="group cursor-pointer overflow-hidden bg-white/3 border-white/10 hover:border-primary/40 hover:shadow-[0_0_20px_rgba(var(--primary-rgb),0.15)] transition-all duration-300"
                  onClick={() => setSelectedCreation(c)}
                >
                  <div className="relative aspect-square bg-black/40 border-b border-white/5 overflow-hidden">
                    {c.original_image_url ? (
                      <img 
                        src={c.original_image_url} 
                        alt={c.object_label || "Creation"} 
                        className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700 ease-out"
                      />
                    ) : (
                      <div className="w-full h-full flex items-center justify-center">
                        <Box className="w-10 h-10 text-white/20" />
                      </div>
                    )}
                    
                    {/* Hover overlay indicator */}
                    <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-center justify-center">
                      <div className="bg-primary/90 text-primary-foreground px-4 py-2 rounded-full font-mono text-sm font-semibold flex items-center gap-2 transform translate-y-4 group-hover:translate-y-0 transition-transform duration-300">
                        <Box className="w-4 h-4" /> View 3D Model
                      </div>
                    </div>
                  </div>
                  
                  <div className="p-4 flex flex-col gap-2">
                    <h3 className="font-mono font-semibold text-tech-fg truncate">
                      {c.object_label || "Untitled Model"}
                    </h3>
                    <div className="flex items-center justify-between mt-1">
                      <div className="flex items-center gap-1.5 text-tech-muted text-[10px] font-mono">
                        <Calendar className="w-3 h-3" />
                        {new Date(c.created_at || "").toLocaleDateString()}
                      </div>
                      
                      {c.reviews && c.reviews.length > 0 && (
                        <div className="flex items-center gap-1 text-yellow-400">
                          <Star className="w-3.5 h-3.5 fill-current" />
                          <span className="text-[11px] font-bold font-mono">{avgRating.toFixed(1)}</span>
                          <span className="text-white/30 text-[10px] font-mono">({c.reviews.length})</span>
                        </div>
                      )}
                    </div>
                  </div>
                </Card>
              );
            })}
          </div>

          {hasMore && (
            <div className="mt-12 flex justify-center">
              <Button 
                variant="outline" 
                onClick={handleLoadMore} 
                disabled={loadingMore}
                className="font-mono bg-white/5 border-white/10 hover:bg-white/10 w-full max-w-xs"
              >
                {loadingMore ? (
                  <><Loader2 className="w-4 h-4 mr-2 animate-spin" /> Loading...</>
                ) : (
                  <><Plus className="w-4 h-4 mr-2" /> Load More</>
                )}
              </Button>
            </div>
          )}
        </>
      )}

      {/* Detail Modal */}
      {selectedCreation && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-black/80 backdrop-blur-md animate-in fade-in duration-200">
          <div 
            className="absolute inset-0" 
            onClick={() => setSelectedCreation(null)} 
          />
          <div className="relative w-full max-w-5xl max-h-full bg-tech-bg border border-white/10 rounded-2xl shadow-2xl flex flex-col md:flex-row overflow-hidden animate-in zoom-in-95 duration-300">
            
            {/* Close button */}
            <button 
              onClick={() => setSelectedCreation(null)}
              className="absolute top-4 right-4 z-10 w-8 h-8 flex items-center justify-center rounded-full bg-black/50 text-white hover:bg-white/20 backdrop-blur-sm transition-colors"
            >
              <X className="w-4 h-4" />
            </button>

            {/* 3D Viewer Area */}
            <div className="w-full md:w-2/3 h-[40vh] md:h-[80vh] bg-black/30 relative border-b md:border-b-0 md:border-r border-white/10">
               <model-viewer
                  src={selectedCreation.glb_model_url ?? selectedCreation.raw_glb_url}
                  auto-rotate="true"
                  camera-controls="true"
                  loading="eager"
                  style={{ width: "100%", height: "100%", background: "transparent" }}
                />
            </div>

            {/* Details & Reviews Area */}
            <div className="w-full md:w-1/3 h-[50vh] md:h-[80vh] flex flex-col bg-tech-bg overflow-y-auto">
              <div className="p-6 border-b border-white/10">
                <h2 className="text-xl font-bold text-tech-fg font-mono mb-2">
                  {selectedCreation.object_label || "Untitled Model"}
                </h2>
                <div className="flex flex-col gap-2 text-xs text-tech-muted font-mono">
                  <div className="flex items-center gap-2">
                    <Calendar className="w-4 h-4 opacity-50" />
                    <span>Created on {new Date(selectedCreation.created_at || "").toLocaleDateString()}</span>
                  </div>
                  {(selectedCreation.refined_vertices || selectedCreation.raw_vertices) && (
                    <div className="flex items-center gap-2 mt-1">
                      <Box className="w-4 h-4 opacity-50" />
                      <span>{selectedCreation.refined_vertices || selectedCreation.raw_vertices} Vertices</span>
                    </div>
                  )}
                </div>
              </div>

              <div className="p-6 flex-1">
                <h3 className="text-sm font-semibold text-white/80 font-mono tracking-wider uppercase mb-4">
                  Community Feedback
                </h3>
                
                {selectedCreation.reviews && selectedCreation.reviews.length > 0 ? (
                  <div className="flex flex-col gap-4">
                    {selectedCreation.reviews.map((review) => (
                      <div key={review.id} className="bg-white/5 p-4 rounded-xl border border-white/5">
                        <div className="flex items-center justify-between mb-2">
                          <div className="flex items-center gap-2 text-xs font-semibold text-tech-fg">
                            <User className="w-3.5 h-3.5 opacity-50" />
                            {review.reviewer_name || "Anonymous"}
                          </div>
                          <div className="flex items-center gap-0.5 text-yellow-400">
                            {Array.from({ length: 5 }).map((_, i) => (
                              <Star
                                key={i}
                                className={`w-3 h-3 ${
                                  i < (review.rating ?? 0) ? "fill-current" : "text-white/10"
                                }`}
                              />
                            ))}
                          </div>
                        </div>
                        {review.comment && (
                          <p className="text-xs text-tech-muted leading-relaxed mt-2 italic">
                            "{review.comment}"
                          </p>
                        )}
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className="text-center py-10 opacity-50">
                    <Star className="w-8 h-8 mx-auto mb-2 opacity-20" />
                    <p className="text-xs font-mono">No reviews yet.</p>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
